// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBothu1fY6X_MXYGcfPk8KNEboM2knPGdI',
    appId: '1:166767829631:web:d557c089a3d8bbe47cd54a',
    messagingSenderId: '166767829631',
    projectId: 'mali-prod',
    authDomain: 'mali-prod.firebaseapp.com',
    storageBucket: 'mali-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGII9oRNGjJVAUeDustKOoWEbdezlkQX8',
    appId: '1:166767829631:android:ea47ff1ac00f1bd07cd54a',
    messagingSenderId: '166767829631',
    projectId: 'mali-prod',
    storageBucket: 'mali-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK1Y91HHPGAZxtnrmq4Jfs3gqYI66WZXQ',
    appId: '1:166767829631:ios:5ef8b00214f306437cd54a',
    messagingSenderId: '166767829631',
    projectId: 'mali-prod',
    storageBucket: 'mali-prod.firebasestorage.app',
    iosBundleId: 'com.example.mali03',
  );
}
